### ISSUE TITLE
Wrong version number in About dialog

### ISSUE THREAD

**Issue by MikaVainio** [Raision-seudun-koulutuskuntayhtyma/pyQT5-harjoituksia#1]
Versionumero ei muutu, vaan on kiinteästi 3.1. Pitäisi näyttää `app.dat`:n numero
![Inventor_FjFl0lEJxa](https://user-images.githubusercontent.com/24242044/130205189-e8d7c9eb-fea7-49fb-aa47-3819dae863fe.png)

**Comment by marilounavaararaseko** [comment]
Mielestäni tässä ei ole mitään vikaa. Tämä on feature, ei bugi. @MikaVainio
